### ISSUE TITLE
documentalist 1.0

### ISSUE THREAD

**Issue by giladgray** [palantir/documentalist#51]
- [x] constructor type info #49 
- [x] static members in interfaces #49 
- [x] get files in order #50
- [x] README #52 
- [x] enum type: `Kind.Class`, not just `Class` #53 
- [x] index signatures! `{ [key: string]: IType }` #59 
- [x] `sourceUrl` field is better than `fileName` #60 
- [ ] type arguments in class name
- [ ] release notes
- [ ] windows build #35 
- [ ] client interfaces consumption
- [ ] output built files in `/lib/` paths instead of `/dist/`

**Comment by adidahiya** [comment]
added an item to the list: refactor distribution file paths to match https://github.com/palantir/blueprint/pull/2002
